author: "jens-a-e"
description: "a simple db test for cross compilation with xgo"
filesets:
  includes:
  - README.md
  - LICENSE
  - conf
  excludes:
  - \.git
  - .*\.go
  depth: 3
settings:
  targetdir: ""
  outfiles: []
  build: test -d Godeps && go(){ godep go "$@";} ; go install -v
